version: "3"
services:
  app:
    image: firefox-xdock:latest
    build: .
    environment:
      - DISPLAY=${DISPLAY}
      - XAUTH_TOKEN=${XAUTH_TOKEN}
      - EXEC_PATH=${EXEC_PATH}
    user: "1000:1000"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./data/datagrip:/home/datagrip
      - ./datagrip.sh:/home/datagrip/bin/datagrip.sh      
    command:
      - "/home/datagrip/bin/datagrip.sh"
    network_mode: host
